### ISSUE TITLE
is there a way to improve compdef performance?

### ISSUE THREAD

**Issue by srouquette** [mattmc3/ez-compinit#2]
I'm currently optimizing my setup, and I check the startup time with `zprofrc`  
with `zstyle ':plugin:ez-compinit' 'compstyle' 'zshzoo'`

compdef is number one: `1)   12         311,67    25,97   54,50%    311,67    25,97   54,50%  compdef`

I tried with `zstyle ':plugin:ez-compinit' 'use-cache' 'yes'` or `zstyle ':plugin:ez-compinit' 'compstyleinit' 'defer' 'yes'` but it doesn't change anything.

Maybe using another compstyle, but I don't know what they do differently.

Maybe this is normal, but I'm new to this.

**Comment by mattmc3** [comment]
There's not a lot I can do about actual `compdef` calls since that's built-in to Zsh, but your question got me to  evaluate how I was handling the compdef queuing within this plugin, which I can control. You're right - it was too slow. I ran some zprof tests, and pushed a new commit just now that optimized it. Try updating please.

Old version:

```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)  104          27.17     0.26   97.71%     27.17     0.26   97.71%  foo_compdef
 2)    1           0.64     0.64    2.29%      0.64     0.64    2.29%  foo_compinit
```

New version:

```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1           0.79     0.79   72.04%      0.79     0.79   72.04%  bar_compinit
 2)  104           0.31     0.00   27.96%      0.31     0.00   27.96%  bar_compdef
```

That should speed you up quite a bit. Let me know.

**Comment by srouquette** [comment]
haha nice, thank you  😃 

edit: lol, it's a lot faster on my side now. I was searching in the top position, it's 23 now 😅   
`23)   11           0,16     0,01    0,05%      0,16     0,01    0,05%  compdef`

**Comment by srouquette** [comment]
Regarding the different compstyles, do you have some recommendations?  
I used zshzoo because it was the one you gave in the readme. But what are the differences?

**Comment by mattmc3** [comment]
> Regarding the different compstyles, do you have some recommendations?

Not really. Try them out and use what you like.
